Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the keypair
  EnvironmentName:
    Description: Select the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  MyVpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC for this deployment

Mappings:
  MyRegionMap:
    us-east-2:
      HVM64: ami-0ae9f87d24d606be4
    us-east-1:
      HVM64: ami-02457590d33d576c3
  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.small
  MySecurityMap:
    dev:
      CidrIp: 0.0.0.0/0
    prod:
      CidrIp: 0.0.0.0/0

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      VpcId: !Ref MyVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !FindInMap
            - MySecurityMap
            - !Ref EnvironmentName
            - CidrIp

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName
      SecurityGroupIds:
        - !Ref  SSHSecurityGroup

  

      
    
